# Generated by Django 4.2.16 on 2024-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitChat', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
